### ISSUE TITLE
Build product flavour with transitive dependencies

### ISSUE THREAD

**Issue by rahulraj64** [mirceanis/multi-flavor-lib-demo#4]
When we build the library without specifying the product flavor, it correctly builds the library module specified using 'defaultPublishConfig' (AAR file along all of the transitive dependencies specified in that module) so that the consumer of the library do not require to include the dependencies of the library module. This works fine.
`implementation "com.github.mirceanis.multi-flavor-lib-demo:matterlib:$library_version"`

But, when we try to build a particular product flavor by using 
`implementation "com.github.mirceanis:multi-flavor-lib-demo:$library_version:solid@aar"`
It does not include the transitive dependencies of the library module and the consumer of the library gets runtime exceptions stating that the class files could not be found. So when we build the product flavor, how to include all of the dependencies specified inside that library so that the consumer of the library do not require to include the dependencies themselves?

**Comment by rahulraj64** [comment]
Hi @mirceanis 
Any Idea, How to implement this? I have an urgency and no solution found anywhere.

**Comment by mirceanis** [comment]
@rahulraj64 I assume you are referring to the single-library with multi-flavor example.
In this repo I'm not dealing with dependencies, yet and I don't have the time now to investigate this.
It would help if you shared a project that clearly shows the failure.
